# Generated by Django 2.2.7 on 2019-11-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191105_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='endpoint',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
