# Generated by Django 2.2.7 on 2019-11-05 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191105_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='endpoint',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
